### PR TITLE
fix(collapse-object-array-property)

### LINKED ISSUE #34: Regression: can't close object/array once they're expanded
Caught by @Te7a-Houdini

### PR DESCRIPTION
**Pull request by HugoDF**
Closes #34

- fix childId match regex (had a `*` instead of `.`)
  - this is actually the main change, see https://github.com/Te7a-Houdini/alpinejs-devtools/pull/36/files#diff-ce89d3d52d88bf27196347b55dd78924R77
- refactor loose checks in state.js 
- formats state.js
- adds test for arrow functionality

### CODE REVIEW

File: packages/shell-chrome/src/state.js [hunk 1]
```diff
@@ -1,185 +1,185 @@
...
-          ].isArrowDown;
-        }
+    renderComponentsFromBackend(components) {
+        components.forEach((component, index) => {
+            component.index = index;
+            component.isOpened = this.renderedComponentId == component.id;
+
+            component.flattenedData = flattenData(component.data);
+
+            component.flattenedData.forEach((d) => {
```
Comment (ryangjchandler) [inline packages/shell-chrome/src/state.js:17]: This is a pretty gnarly forEach loop, is there anything else we can do to make it tidier?

Comment (HugoDF) [reply packages/shell-chrome/src/state.js:17]: I wouldn't touch it until we've got some sort of tests in place

**Comment by HugoDF** [comment]
just FYI I'm adding tests for this one 😄
