### PR TITLE
fix(number-input) chore(remove-eval) 

### LINKED ISSUE #26: Number properties edited through Devtools turn into strings
When I edit a value that's a number, I expect a number value to be set (currently being set to the string representation of the number)

PS. I'm creating this issue after fixing it mainly for accountability purposes eg. tracking which release it's a part of

### PR DESCRIPTION
**Pull request by HugoDF**
Closes #26 
Refactor of backend.js to remove `eval` since it's not strictly necessary & causes a Rollup warning.

- **fix**: setting non-top-level properties to boolean/number
- **fix**: coerce number inputs to number values before updating them in Alpine

Changes:

- create a `set` function inspired by `lodash.set` (see https://lodash.com/docs#set) so we can do `set(data, 'array.0.property.nestedProperty', 'newValue')` instead of using `eval`.
- use `set` in backend.js instead of `eval`.
- format all edited files to 4-space indent
- refactor `flattenSingleAttribute` for Array/Object to be more compact
- change path separator from `*` eg. `array*0*property` to `.`, eg. `array.0.property`

### CODE REVIEW

File: packages/shell-chrome/src/utils.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
 export function flattenData(data) {
     let flattenedData = [];
 
+    console.log(data);
```
Comment (ryangjchandler) [inline packages/shell-chrome/src/utils.js:4]: Rogue console.log()

File: packages/shell-chrome/src/utils.js [hunk 2]
```diff
@@ -55,51 +66,30 @@ export function flattenSingleAttribute(
...
+                `${elementId}.${index}`,
+                elementId
             );
-        }
+        });
     } else if (value instanceof Object) {
-        margin = margin + 10;
-
-        for (var objectKey in value) {
+        Object.keys(value).forEach((objectKey) => {
```
Comment (ryangjchandler) [inline packages/shell-chrome/src/utils.js:82]: We can safely use `Object.entries()` here to get the index & value, since Chrome & Firefox both support it, removes the need for `value[objectKey]`.

**Comment by HugoDF** [comment]
@ryangjchandler thanks for the comments, should be fixed now
